[metadata]
name = "{{PACK_NAME}}"
description = "Atlas starter template"

[versions]
mc = "1.21.1"
modloader = "neoforge"
modloader_version = "21.1.219"

[cli]
pack_id = "oPPfwdNcEl5AyRxaI0aE3"
hub_url = "https://atlas.nathanm.org"
default_channel = "dev"









