[metadata]
name = "Cobblemon"
side = "both"
project_url = "https://modrinth.com/mod/cobblemon"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "MdwFAVRL"
version = "S1TrAn8c"
url = "https://cdn.modrinth.com/data/MdwFAVRL/versions/S1TrAn8c/Cobblemon-neoforge-1.7.3%2B1.21.1.jar"

[download.hashes]
sha512 = "609b435cf0cfedbfb8d54f6355b37b547306c0d3a3aab241ba5643ed8dc82e084d5a7d80d9661b786f9a0fa295b506be78e608281f5972019e6cff691aee50df"
