[metadata]
name = "Iris Shaders"
side = "client"
project_url = "https://modrinth.com/mod/iris"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "YL57xq9U"
version = "t3ruzodq"
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/t3ruzodq/iris-neoforge-1.8.12%2Bmc1.21.1.jar"

[download.hashes]
sha512 = "57b8026a3c3c433cf6123d63dc6ce7e11f6d480a72926370db1fc7f2b06059bc16a753ecd7e7af659c19e90b592103196b0e89585ce4f0744a4ca433f59bcf1a"
