[metadata]
name = "Kotlin for Forge"
side = "both"
project_url = "https://modrinth.com/mod/kotlin-for-forge"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "ordsPcFz"
version = "NrSebcsG"
url = "https://cdn.modrinth.com/data/ordsPcFz/versions/NrSebcsG/kotlinforforge-5.11.0-all.jar"

[download.hashes]
sha512 = "b32faa6d616511aff4f8b32197877c53b9f8bee103884ec37c632b5d017bb59a498ec971b68d8d94787043b0c5be666a330b61d285033c341bff83ac28a90992"
