[metadata]
name = "Sodium"
side = "client"
project_url = "https://modrinth.com/mod/sodium"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "AANobbMI"
version = "Pb3OXVqC"
url = "https://cdn.modrinth.com/data/AANobbMI/versions/Pb3OXVqC/sodium-neoforge-0.6.13%2Bmc1.21.1.jar"

[download.hashes]
sha512 = "ce58f34d05d96c0a109a5cea23c741f6bdb2e6be31fc087c5989274cefca5f10ba0c08c62083cf554a51f2c7667bf46e4164383f675c844e77633aef2659996b"
